-- ProjNav VHDL simulation template: single_cycle_core_testbench.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
